version: "3.8"

services:
  cms:
    restart: always
    container_name: cms_ms
    build:
      context: .
      network: host
      dockerfile: ./docker/dev/Dockerfile
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/app/media/
    env_file:
      - .env.development
    expose:
      - 8008

  nginx:
    build:
      dockerfile: Dockerfile
      network: host
      context: ./nginx
    container_name: cms_ms_nginx
    restart: always
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/app/media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cms

volumes:
  static_volume:
  media_volume: