# Generated by Django 4.0.5 on 2022-07-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_facultyusermodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='support',
        ),
    ]
