# Generated by Django 4.0.5 on 2022-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyusermodel',
            name='description',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
