# Generated by Django 4.0.5 on 2022-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyusermodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='facultyusermodel',
            name='expertise',
            field=models.CharField(default='test', max_length=100, verbose_name='Expertise'),
            preserve_default=False,
        ),
    ]
